"""
Setup script for Anonymous Chat Bot
Helps configure the bot and verify settings
"""

import os
import sys

def create_env_file():
    """Interactive setup for .env file"""
    print("=" * 60)
    print("Anonymous Chat Bot - Setup Wizard")
    print("=" * 60)
    print()
    
    if os.path.exists('.env'):
        response = input(".env file already exists. Overwrite? (y/n): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print("Let's configure your bot!\n")
    
    # Bot Token
    print("1. Bot Token")
    print("   Get this from @BotFather on Telegram")
    print("   Format: 1234567890:ABCdefGHIjklMNOpqrsTUVwxyz")
    bot_token = input("   Enter your bot token: ").strip()
    
    if not bot_token or ':' not in bot_token:
        print("   ⚠️  Invalid token format!")
        sys.exit(1)
    
    # Admin IDs
    print("\n2. Admin User IDs")
    print("   Get your user ID from @userinfobot")
    print("   You can add multiple IDs separated by commas")
    admin_ids = input("   Enter admin ID(s): ").strip()
    
    if not admin_ids:
        print("   ⚠️  At least one admin ID is required!")
        sys.exit(1)
    
    # Required Channels
    print("\n3. Required Channels (Optional)")
    print("   Users must subscribe to these channels")
    print("   Format: @channel1,@channel2,@channel3")
    print("   Leave empty to skip forced subscription")
    required_channels = input("   Enter channel(s): ").strip()
    
    # VIP Price
    print("\n4. VIP Membership Price")
    print("   Price in Telegram Stars (default: 100)")
    vip_price = input("   Enter VIP price [100]: ").strip()
    if not vip_price:
        vip_price = "100"
    
    # Create .env file
    env_content = f"""# Anonymous Chat Bot Configuration
# Generated by setup script

# Bot token from @BotFather
BOT_TOKEN={bot_token}

# Admin user IDs (comma-separated)
ADMIN_IDS={admin_ids}

# Required channels for subscription (comma-separated)
REQUIRED_CHANNELS={required_channels}

# VIP price in Telegram Stars
VIP_PRICE_STARS={vip_price}

# Database path
DATABASE_PATH=chatbot.db
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n" + "=" * 60)
    print("✅ Configuration saved to .env file!")
    print("=" * 60)
    print()
    
    # Additional setup instructions
    print("Next steps:")
    print()
    print("1. Install dependencies:")
    print("   pip install -r requirements.txt")
    print()
    
    if required_channels:
        print("2. Make your bot admin of required channels:")
        for channel in required_channels.split(','):
            if channel.strip():
                print(f"   - Add bot to {channel.strip()} as administrator")
        print()
    
    print("3. Set bot commands in @BotFather:")
    print("   Send /setcommands and paste:")
    print("""
   start - Start the bot
   search - Find a chat partner
   stop - End current chat
   next - Find next partner
   profile - View your profile
   vip - Get VIP status
   rules - View chat rules
   help - Show help
   """)
    
    print("4. Enable payments in @BotFather (for VIP feature):")
    print("   - Go to @BotFather → Payments")
    print("   - Connect payment provider or use Telegram Stars")
    print()
    
    print("5. Run the bot:")
    print("   python bot.py")
    print()
    print("=" * 60)
    print("Setup complete! Good luck with your bot! 🚀")
    print("=" * 60)

def verify_setup():
    """Verify bot setup"""
    print("\nVerifying setup...")
    print()
    
    issues = []
    
    # Check .env file
    if not os.path.exists('.env'):
        issues.append("❌ .env file not found")
    else:
        print("✅ .env file found")
    
    # Check required files
    required_files = ['bot.py', 'database.py', 'config.py', 'requirements.txt']
    for file in required_files:
        if not os.path.exists(file):
            issues.append(f"❌ Missing file: {file}")
        else:
            print(f"✅ {file} found")
    
    # Try importing dependencies
    try:
        import telegram
        print("✅ python-telegram-bot installed")
    except ImportError:
        issues.append("❌ python-telegram-bot not installed (run: pip install -r requirements.txt)")
    
    try:
        import dotenv
        print("✅ python-dotenv installed")
    except ImportError:
        issues.append("❌ python-dotenv not installed (run: pip install -r requirements.txt)")
    
    print()
    
    if issues:
        print("Issues found:")
        for issue in issues:
            print(f"  {issue}")
        print()
        print("Please fix these issues before running the bot.")
        return False
    else:
        print("✅ All checks passed! Your bot is ready to run.")
        print()
        print("Start the bot with: python bot.py")
        return True

if __name__ == '__main__':
    print()
    
    if len(sys.argv) > 1 and sys.argv[1] == 'verify':
        verify_setup()
    else:
        create_env_file()
        print()
        verify_setup()
